config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/about', to: 'about#index'

  get '/contact', to: 'messages#new', as: 'new_message'
  post '/contact', to: 'messages#create', as: 'create_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_path, notice: "Message received"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>I am Adele</h1>

app/views/home/index.html.erb
<div class="promo"><h1>Coming Soon</h1></div>

<div class="social">
  <a href="https://twitter.com/adelekyriacou">
    <%= image_tag("twitter", size: "50") %></a>

  <a href="https://github.com/adelekyriacou">
    <%= image_tag("github", size: "50") %></a>

  <a href="http://uk.linkedin.com/pub/adele-kyriacou/37/1b1/a45">
    <%= image_tag("linkedin", size: "50") %></a>

  <a href="http://instagram.com/adelekyriacou">
    <%= image_tag("instagram", size: "50") %></a>
</div>

<p>hello@adelekyriacou.com</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no" />

    <title>Adele Kyriacou | Front-End developer and designer</title>

    <meta name="description" content="The website of Adele Kyriacou, Front-End
    developer and designer. " />
    <meta name="keywords" content="Adele Kyriacou, front-end developer, portfolio,
    web developer, web designer, designer, London, CSS3, HTML5" />
    <meta name="author" content="Adele Kyriacou" />

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/nav" %>
    </header>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<h1>Talk to me</h1>

<div class="contact_form">
  <%= form_for @message, url: create_message_url do |f| %>
    <%= notice %>
    <%= @message.errors.full_messages.join(', ') %>

    <div class="contact_form__field">
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>

    <div class="contact_form__field">
      <%= f.email_field :email, placeholder: 'Email' %>
    </div>

    <div class="contact_form__field">
      <%= f.text_area :body, placeholder: 'Message' %>
    </div>

    <div class="contact_form__buttons">
      <%= f.submit 'Send' %>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="nav">
  <%= link_to "Home", root_path %>
  <%= link_to "About", about_path %>
  <%= link_to "Contact", new_message_path %>
</nav>